import { FormEvent, useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, LogOut, Plus, Video } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { invoke, type Meeting } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/dashboard")({ component: Dashboard });

function Dashboard() {
  const { user, profile, loading: authLoading, signOut } = useAuth(); const navigate=useNavigate(); const [meetings,setMeetings]=useState<Meeting[]>([]); const [title,setTitle]=useState(""); const [slug,setSlug]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [showCreate,setShowCreate]=useState(false);
  useEffect(()=>{if(!authLoading&&!user) navigate({to:"/login"});},[authLoading,user,navigate]);
  useEffect(()=>{if(!user)return; supabase.from("meetings").select("id,host_id,title,public_slug,videosdk_meeting_id,status,created_at").eq("host_id",user.id).order("created_at",{ascending:false}).limit(30).then(({data,error})=>{if(error)setError(error.message);else setMeetings((data??[]) as Meeting[])});},[user]);
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const result=await invoke<{meeting:Meeting}>("create-meeting",{title});setMeetings(v=>[result.meeting,...v]);setTitle("");setShowCreate(false);navigate({to:"/meeting/$meetingSlug",params:{meetingSlug:result.meeting.public_slug}});}catch(err){setError(err instanceof Error?err.message:"Could not create meeting");}finally{setBusy(false)}};
  const join=async(e:FormEvent)=>{e.preventDefault();const value=slug.trim();if(!value)return;setBusy(true);setError("");try{await invoke("join-meeting",{slug:value});navigate({to:"/meeting/$meetingSlug",params:{meetingSlug:value}})}catch(err){setError(err instanceof Error?err.message:"Could not join meeting");}finally{setBusy(false)}};
  if(authLoading||!user)return <div className="center-page"><div className="card narrow"><p className="muted">Loading your account…</p></div></div>;
  return <div className="page"><header className="nav"><Link to="/" className="brand"><span className="logo"><Video size={18}/></span>Clear Meet</Link><div className="nav-links"><span className="nav-link">{profile?.display_name||user.email}</span><button className="button secondary" onClick={()=>void signOut()}><LogOut size={16}/>Sign out</button></div></header><main className="container"><div style={{marginTop:42}}><div className="eyebrow">DASHBOARD</div><h1 style={{fontSize:38,letterSpacing:"-.04em",margin:"8px 0"}}>Good to see you, {profile?.display_name?.split(" ")[0]||"there"}.</h1><p className="muted">Create a room or join a meeting link.</p></div>{error&&<div className="error" style={{marginTop:18}}>{error}</div>}<div className="dashboard-grid"><section className="meeting-card"><div className="meeting-row"><div><h2>Start a meeting</h2><p className="muted">Create a secure room with a shareable link.</p></div><button className="button primary" onClick={()=>setShowCreate(v=>!v)}><Plus size={17}/>New meeting</button></div>{showCreate&&<form className="form" onSubmit={create}><div className="field"><label>Meeting title</label><input className="input" autoFocus maxLength={120} required placeholder="Product sync" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="actions"><button className="button primary" disabled={busy}>{busy?"Creating…":"Create & enter"}</button><button type="button" className="button secondary" onClick={()=>setShowCreate(false)}>Cancel</button></div></form>}</section><section className="meeting-card"><h2>Join a meeting</h2><p className="muted">Paste the public meeting code.</p><form className="form" onSubmit={join}><input className="input" placeholder="k7p-x92-mqa" value={slug} onChange={e=>setSlug(e.target.value)}/><button className="button secondary" disabled={busy}>Join meeting <ArrowRight size={16}/></button></form></section></div><section style={{marginTop:28}}><h2>Recent meetings</h2>{meetings.length===0?<div className="meeting-card" style={{marginTop:12}}><p className="muted">No meetings yet. Your first room will appear here.</p></div>:meetings.map(m=><div className="meeting-card" key={m.id} style={{marginTop:12}}><div className="meeting-row"><div><div className="meeting-title">{m.title}</div><div className="meeting-meta">/meeting/{m.public_slug}</div></div><div className="actions" style={{marginTop:0}}><span className="badge">{m.status}</span><Link className="button secondary" to="/meeting/$meetingSlug" params={{meetingSlug:m.public_slug}}>Open <ArrowRight size={15}/></Link></div></div></div>)}</section></main></div>;
}
