import { useEffect, useMemo, useRef, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Camera, CameraOff, Copy, LogOut, Mic, MicOff, MonitorUp, PhoneOff, ShieldCheck, Users, Video } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { invoke, type Meeting } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";

type VideoSDKModule = typeof import("@videosdk.live/react-sdk");

type ParticipantRow = { id:string; meeting_id:string; user_id:string; role:"host"|"co_host"|"participant"; status:"waiting"|"admitted"|"rejected"|"left"|"removed"; joined_at:string|null; profiles?:{display_name:string;avatar_url:string|null}|null };
type MessageRow = { id:string; sender_id:string; message:string; created_at:string; profiles?:{display_name:string}|null };

export const Route = createFileRoute("/meeting/$meetingSlug")({ component: MeetingRoute });

function MeetingRoute(){
 const {user,profile,loading}=useAuth(); const navigate=useNavigate(); const {meetingSlug}=Route.useParams(); const [meeting,setMeeting]=useState<Meeting|null>(null); const [participant,setParticipant]=useState<ParticipantRow|null>(null); const [error,setError]=useState(""); const [loadingRoom,setLoadingRoom]=useState(true); const [token,setToken]=useState(""); const [videoSdk,setVideoSdk]=useState<VideoSDKModule|null>(null); const requestedVideoSession=useRef<string|null>(null);
 useEffect(()=>{if(loading)return;if(!user){sessionStorage.setItem("clear-meet-return",window.location.pathname);void navigate({to:"/login"});return;} let cancelled=false; void (async()=>{try{const result=await invoke<{meeting:Meeting;participant:ParticipantRow}>("join-meeting",{slug:meetingSlug});if(cancelled)return;setMeeting(result.meeting);setParticipant(result.participant);}catch(err){if(!cancelled)setError(err instanceof Error?err.message:"Could not open meeting")}finally{if(!cancelled)setLoadingRoom(false)}})();return()=>{cancelled=true};},[loading,user,meetingSlug,navigate]);
 useEffect(()=>{if(!user||!participant)return; const channel=supabase.channel(`participant-${participant.id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"meeting_participants",filter:`id=eq.${participant.id}`},payload=>setParticipant(payload.new as ParticipantRow)).subscribe(); return()=>{void supabase.removeChannel(channel)};},[user,participant?.id]);
 useEffect(()=>{const status=participant?.status; const meetingId=meeting?.id; const videosdkMeetingId=meeting?.videosdk_meeting_id; if(!meetingId||!participant)return; const sessionKey=`${meetingId}:${participant.id}`; if(status==="rejected"||status==="removed"){requestedVideoSession.current=null;setToken("");setVideoSdk(null);return;} if(status!=="admitted")return; if(!videosdkMeetingId){setError("This meeting has no VideoSDK meeting ID. Please create a new meeting.");return;} if(requestedVideoSession.current===sessionKey)return; requestedVideoSession.current=sessionKey; setError(""); void invoke<{token:string;meetingId:string}>("create-video-token",{meetingId}).then(v=>{if(!v.token||!v.meetingId||v.meetingId!==videosdkMeetingId)throw new Error("Video service returned an invalid meeting token or meeting ID.");setToken(v.token)}).catch(err=>{if(requestedVideoSession.current===sessionKey)requestedVideoSession.current=null;setToken("");setVideoSdk(null);setError(err instanceof Error?err.message:"Could not authorize video")});},[participant?.id,participant?.status,meeting?.id,meeting?.videosdk_meeting_id]);
 useEffect(()=>{if(!token||typeof window==="undefined")return; let active=true; void import("@videosdk.live/react-sdk").then(module=>{if(active)setVideoSdk(module)}).catch(err=>{if(active)setError(err instanceof Error?err.message:"Could not load video service")});return()=>{active=false}},[token]);
 if(loading||loadingRoom)return <div className="center-page"><div className="card narrow"><div className="eyebrow">CLEAR MEET</div><h1>Opening meeting…</h1><p className="muted">Checking your meeting access.</p></div></div>;
 if(error&&!meeting)return <div className="center-page"><div className="card narrow"><div className="error">{error}</div><Link className="button secondary" style={{marginTop:14}} to="/dashboard">Back to dashboard</Link></div></div>;
 if(!meeting||!participant)return null;
 if(participant.status==="waiting")return <WaitingRoom meeting={meeting} participant={participant}/>;
 if(participant.status==="rejected"||participant.status==="removed")return <div className="center-page"><div className="card narrow"><div className="eyebrow">ACCESS ENDED</div><h1>You can’t enter this meeting</h1><p className="muted">The host has {participant.status === "removed" ? "removed you" : "declined your request"}.</p><Link className="button primary" to="/dashboard">Return to dashboard</Link></div></div>;
 if(!token||!videoSdk)return <div className="center-page"><div className="card narrow"><div className="eyebrow">AUTHORIZED</div><h1>{error?"Video connection failed":"Joining meeting…"}</h1><p className="muted">{error||"You can join without camera or microphone access. Turn them on any time from the meeting controls."}</p>{error&&<Link className="button secondary" style={{marginTop:14}} to="/dashboard">Back to dashboard</Link>}</div></div>;
 return <videoSdk.MeetingProvider token={token} config={{meetingId:meeting.videosdk_meeting_id!,name:profile?.display_name||user?.email||"Guest",micEnabled:false,webcamEnabled:false}} joinWithoutUserInteraction><MeetingRoom meeting={meeting} participant={participant} sdk={videoSdk}/>{error&&<div className="error" style={{position:"fixed",bottom:90,left:16,right:16,zIndex:20}}>{error}</div>}</videoSdk.MeetingProvider>;
}

function WaitingRoom({meeting,participant}:{meeting:Meeting;participant:ParticipantRow}){return <div className="waiting"><div className="card narrow"><div className="icon-box" style={{margin:"0 auto 18px"}}><Users size={19}/></div><div className="eyebrow">WAITING ROOM</div><h1>{meeting.title}</h1><p className="muted">You’re in the waiting room. The host will let you in when ready.</p><div className="badge" style={{marginTop:10}}>Request pending</div><button className="button secondary" style={{marginTop:22}} onClick={()=>window.history.back()}><LogOut size={16}/>Leave</button></div></div>}

function MeetingRoom({meeting,participant,sdk}:{meeting:Meeting;participant:ParticipantRow;sdk:VideoSDKModule}){
 const {user}=useAuth(); const navigate=useNavigate(); const [chat,setChat]=useState<MessageRow[]>([]); const [text,setText]=useState(""); const [people,setPeople]=useState<ParticipantRow[]>([]); const [copied,setCopied]=useState(false); const useMeeting=sdk.useMeeting;
 const {meetingState}=useMeeting({onMeetingJoined:()=>console.log("[VideoSDK] meeting joined"),onMeetingLeft:()=>console.log("[VideoSDK] meeting left"),onError:error=>console.error("[VideoSDK] meeting error",error)});
 const load=async()=>{const {data}=await supabase.from("meeting_participants").select("id,meeting_id,user_id,role,status,joined_at,profiles(display_name,avatar_url)").eq("meeting_id",meeting.id).order("created_at");setPeople((data??[]) as unknown as ParticipantRow[]);const {data:msgs}=await supabase.from("meeting_messages").select("id,sender_id,message,created_at,profiles(display_name)").eq("meeting_id",meeting.id).order("created_at").limit(100);setChat((msgs??[]) as unknown as MessageRow[])};
 useEffect(()=>{void load();const pch=supabase.channel(`meeting-${meeting.id}`).on("postgres_changes",{event:"*",schema:"public",table:"meeting_participants",filter:`meeting_id=eq.${meeting.id}`},()=>void load()).on("postgres_changes",{event:"INSERT",schema:"public",table:"meeting_messages",filter:`meeting_id=eq.${meeting.id}`},payload=>setChat(v=>[...v,payload.new as MessageRow])).subscribe();return()=>{void supabase.removeChannel(pch)}},[meeting.id]);
 const send=async()=>{const value=text.trim();if(!value||!user)return;setText("");const {error}=await supabase.from("meeting_messages").insert({meeting_id:meeting.id,sender_id:user.id,message:value});if(error)console.error(error)};
 const leave=async()=>{try{await invoke("leave-meeting",{meetingId:meeting.id})}finally{await navigate({to:"/dashboard"})}};
 const admit=async(id:string)=>{try{await invoke("admit-participant",{meetingId:meeting.id,participantId:id})}catch(e){console.error(e)}}; const reject=async(id:string)=>{try{await invoke("reject-participant",{meetingId:meeting.id,participantId:id})}catch(e){console.error(e)}}; const isHost=participant.role==="host"||participant.role==="co_host";
 const copy=()=>{void navigator.clipboard.writeText(`${window.location.origin}/meeting/${meeting.public_slug}`).then(()=>{setCopied(true);window.setTimeout(()=>setCopied(false),1500)}).catch(console.error)};
 if(meetingState!=="JOINED")return <div className="meeting-page"><header className="meeting-header"><Link to="/dashboard" className="brand"><span className="logo"><Video size={17}/></span><span style={{maxWidth:240,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{meeting.title}</span></Link></header><main className="meeting-main"><div className="card narrow"><div className="eyebrow">CONNECTING</div><h1>{meetingState==="JOINING"?"Joining meeting…":"Preparing meeting…"}</h1><p className="muted">Camera and microphone are off. You can enable them after you join.</p></div></main></div>;
 return <div className="meeting-page"><header className="meeting-header"><Link to="/dashboard" className="brand"><span className="logo"><Video size={17}/></span><span style={{maxWidth:240,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{meeting.title}</span></Link><div className="actions" style={{marginTop:0}}><button className="button secondary" onClick={copy}><Copy size={15}/>{copied?"Copied":"Share"}</button>{isHost&&<span className="badge"><ShieldCheck size={13}/> Host</span>}</div></header><main className="meeting-main"><VideoStage sdk={sdk}/><div className="meeting-card"><div className="meeting-row"><h2>People</h2><span className="badge">{people.filter(p=>p.status==="admitted").length} admitted</span></div>{isHost&&people.some(p=>p.status==="waiting")&&<div style={{marginTop:14}}><div className="eyebrow">WAITING</div>{people.filter(p=>p.status==="waiting").map(p=><div className="meeting-row" key={p.id} style={{padding:"10px 0",borderBottom:"1px solid #eef0f4"}}><span>{p.profiles?.display_name||"Guest"}</span><div className="actions" style={{marginTop:0}}><button className="button primary" onClick={()=>void admit(p.id)}>Admit</button><button className="button ghost" onClick={()=>void reject(p.id)}>Reject</button></div></div>)}</div>}{chat.length>0&&<div style={{marginTop:18,maxHeight:180,overflowY:"auto",background:"#f8fafc",borderRadius:12,padding:10}}>{chat.map(m=><div key={m.id} style={{fontSize:13,padding:"4px 0"}}><b>{m.profiles?.display_name||"Guest"}</b>: {m.message}</div>)}</div>}<div className="actions" style={{marginTop:12}}><input className="input" style={{flex:1}} placeholder="Message the meeting…" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}}/><button className="button secondary" onClick={()=>void send()}>Send</button></div></div></main><MeetingControls onLeave={leave} sdk={sdk} joined={meetingState==="JOINED"}/></div>;
}

function VideoStage({sdk}:{sdk:VideoSDKModule}){const useMeeting=sdk.useMeeting;const {participants,meetingState}=useMeeting();const ids=useMemo(()=>Array.from(participants.keys()),[participants]);if(meetingState!=="JOINED")return null;return <div className="video-grid">{ids.map(id=><ParticipantTile key={id} participantId={id} sdk={sdk}/>)}</div>}
function ParticipantTile({participantId,sdk}:{participantId:string;sdk:VideoSDKModule}){const useParticipant=sdk.useParticipant;const {webcamStream,webcamOn,micStream,micOn,isLocal,displayName}=useParticipant(participantId);const videoRef=useRef<HTMLVideoElement>(null);const audioRef=useRef<HTMLAudioElement>(null);useEffect(()=>{if(videoRef.current){if(webcamOn&&webcamStream){const stream=new MediaStream();stream.addTrack(webcamStream.track);videoRef.current.srcObject=stream;void videoRef.current.play().catch(()=>{})}else videoRef.current.srcObject=null}},[webcamStream,webcamOn]);useEffect(()=>{if(audioRef.current){if(micOn&&micStream){const stream=new MediaStream();stream.addTrack(micStream.track);audioRef.current.srcObject=stream;void audioRef.current.play().catch(()=>{})}else audioRef.current.srcObject=null}},[micStream,micOn]);return <div className="video-tile">{webcamOn?<video ref={videoRef} autoPlay playsInline muted={isLocal}/>:<div className="avatar-fallback">{(displayName||"?").slice(0,1).toUpperCase()}</div>}<audio ref={audioRef} autoPlay playsInline muted={isLocal}/><span className="tile-label">{displayName||"Participant"}{micOn?"":" · muted"}</span></div>}
function MeetingControls({onLeave,sdk,joined}:{onLeave:()=>Promise<void>;sdk:VideoSDKModule;joined:boolean}){const useMeeting=sdk.useMeeting;const {toggleMic,toggleWebcam,enableScreenShare,micOn,webcamOn}=useMeeting();const [sharing,setSharing]=useState(false);const [busy,setBusy]=useState<"mic"|"webcam"|"screen"|null>(null);const action=async(kind:"mic"|"webcam"|"screen",fn:()=>unknown)=>{if(!joined||busy)return;setBusy(kind);try{await Promise.resolve(fn())}catch(error){console.error("VideoSDK action failed",error)}finally{setBusy(null)}};return <div className="control-bar"><button disabled={!joined||busy!==null} className={`control ${micOn?"active":""}`} title={joined?"Microphone":"Joining meeting…"} onClick={()=>void action("mic",()=>toggleMic())}>{micOn?<Mic size={19}/>:<MicOff size={19}/>}</button><button disabled={!joined||busy!==null} className={`control ${webcamOn?"active":""}`} title={joined?"Camera":"Joining meeting…"} onClick={()=>void action("webcam",()=>toggleWebcam())}>{webcamOn?<Camera size={19}/>:<CameraOff size={19}/>}</button><button disabled={!joined||busy!==null} className={`control ${sharing?"active":""}`} title={joined?"Share screen":"Joining meeting…"} onClick={()=>void action("screen",async()=>{await enableScreenShare();setSharing(true)})}><MonitorUp size={19}/></button><button className="control leave" title="Leave" onClick={()=>void onLeave()}><PhoneOff size={19}/></button></div>}
